language: objective-c
osx_image: xcode11
env:
  - DESTINATION="OS=13.0,name=iPhone 11" SCHEME="PostalAddressRow" SDK=iphonesimulator

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS
- gem install xcpretty --no-document --quiet

script:
- xcodebuild clean build -project PostalAddressRow.xcodeproj -scheme "$SCHEME" -sdk "$SDK"
- xcodebuild -project PostalAddressRow.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
  -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
